
    module.exports.config = {
      name: "nword",
      version: "1.0.0",
      hasPermission: 0,
      credits: "Generated by AI",
      description: "This is a dynamically generated command.",
      usePrefix: true,
      allowPrefix: true,
      commandCategory: "custom",
      cooldowns: 5
    };

    module.exports.run = async function({ api, event, args }) {
      const { threadID, messageID } = event;
      api.sendMessage("Nigga", threadID, messageID);
    };
  